name = "crusty"
type = "javascript"
account_id = "85eee8deb2af3bc95d24222571ae2f10"
workers_dev = true
route = ""
zone_id = ""
main = "./.cloudflare/worker.js"
compatibility_date = "2023-04-22"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = "./.cloudflare/public"
